# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc:6

build:
  stage: build
  before_script: 
      - apt update && apt -y install make autoconf cmake qemu
  script:
    - ./configure ci
    - mkdir build
    - cd build
    - cmake -DCI_BUILD=ON ..
    - make iso
    - qemu-system-i368 -cdrom build/os.iso -nographic -no-reboot
  artifacts:
    paths:
      - "build/os.iso"
  cache:
    paths:
      - "build/"
