image: mrokkk/kernel-dev

build:
  stage: build
  script:
    - ./configure ci
    - mkdir -p build
    - cd build
    - cmake -DCI_BUILD=ON ..
    - make runqemu
    - ./runqemu-nographic
  artifacts:
    paths:
      - "build/os.iso"
      - "build/runqemu*"
  cache:
    paths:
      - "build/"
  tags:
      - shared
